language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

services: sqlite

script:
  - python setup.py install
  - python tests/sample_db_tests.py

notifications:
  email: false
