language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

<<<<<<< Updated upstream
script: python tests/sample_db_tests.py
=======
script:
  - python setup.py
  - python tests/sample_db_tests.py
>>>>>>> Stashed changes

notifications:
  email: false
